# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unclebudget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='transfer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_set', to='unclebudget.Budget'),
        ),
    ]
